# Generated by Django 3.1.13 on 2021-09-07 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_auto_20210907_0508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['domain'], 'verbose_name': 'site', 'verbose_name_plural': 'sites'},
        ),
    ]
