# Generated by Django 3.1.13 on 2021-09-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPageText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('under_form_text', models.TextField(verbose_name='Text under the form')),
                ('after_form_text_title1', models.CharField(max_length=255, verbose_name='First text title after the form')),
                ('after_form_text_title2', models.CharField(max_length=255, verbose_name='Second text title after the form')),
                ('after_form_text_description1', models.TextField(verbose_name='First text description after the form')),
                ('after_form_text_description2', models.TextField(verbose_name='Second text description after the form')),
                ('copyright_text', models.TextField(verbose_name='Copyright text')),
            ],
            options={
                'verbose_name': 'Index Page Texts',
            },
        ),
    ]
