# Generated by Django 3.1.13 on 2021-09-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0002_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="url",
            field=models.URLField(verbose_name="Real URL"),
        ),
    ]
