# Generated by Django 3.1.13 on 2021-09-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0003_auto_20210908_0845"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="count",
            field=models.PositiveIntegerField(default=0, verbose_name="Click count"),
        ),
    ]
